---
docker_dependencies:
  - acl
  - python3-pip
  - python3-docker
  - python3-requests
  - python3-urllib3
  - python3-virtualenv
  - net-tools
  - iproute2
  - gpg

docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin
  - docker-ce-rootless-extras
  # - docker-scan-plugin

## choose centos docker repo channel enable status
docker_repo:
  channel:
    stable_enabled: true
    
  gpg_url:  https://repo.mecan.ir/repository/ubuntu-docker/gpg # https://download.docker.com/linux/ubuntu/gpg 
  repo_url: https://repo.mecan.ir/repository/ubuntu-docker/    #  https://download.docker.com/linux/
  keyring_path: /etc/apt/keyrings/docker1.asc     

docker_config:
  proxy:
    enable: false
    http_url: "http://127.0.0.1:8123"
    https_url: "http://127.0.0.1:8123"
    no_proxy_url: "hub.mecan.ir,127.0.0.0/8"
  logging:
    enable: true
    labels: "{{ inventory_hostname }}"
    max_file: 5
    max_size: 100M
  mirror_registry:
    enable: true
    urls: "https://hub.mecan.ir"
  insecure_registry:
    enable: true
    urls: "https://test.mecan.ir"
  live_restore:
    enable: true
  experimental:
    enable: true
