---
- name: install docker dependencies
  ansible.builtin.package:
    name: "{{ docker_dependencies }}"
    state: present

- name: add apt signing key (debian)
  ansible.builtin.apt_key:
    url: "{{ docker_repo.gpg_url }}"
    keyring: "{{ docker_repo.keyring_path }}" 

  become: true

- name: change the file permission of keyringsss
  become: true
  ansible.builtin.file:    
    path: "/etc/apt/keyrings"
    mode: '0755'
    state: directory
- name: change the file permission of keyring
  become: true
  ansible.builtin.file:
    path: "{{ docker_repo.keyring_path }}"
    mode: '644'
   
 

- name: install official docker repositories for debian based
  ansible.builtin.template:
    src: etc/apt/sources.list.d/docker-ce.list.j2
    dest: /etc/apt/sources.list.d/docker-ce.list
    mode: 0644
    owner: root
    group: root